### ISSUE TITLE
Chess256 on MacOS

### ISSUE THREAD

**Issue by relipse** [alex65536/Chess256#2]
Hey , I tried to compile on MacOS
I used 
`  {$IFDEF DARWIN}
    EngineName1 = '/Users/tearsfornations/util/lazarus/Chess256/Stockfish/stockfish';
    EngineName2 = '/Users/tearsfornations/util/lazarus/Chess256/Stockfish/stockfish';
    EngineFilter = '*';
    EngineDefExt = '';
    {$DEFINE HAS_ENGINE_NAME}
  {$ENDIF} `

and downloaded stockfish but when I press "Play", I get
Project Chess 256 raised exception class 'EResourceReaderWrongFormatException'

**Comment by relipse** [comment]
But it looks really cool!

**Comment by relipse** [comment]
![image](https://github.com/alex65536/Chess256/assets/408981/580a0dd8-f3f4-4033-a939-3db0520430ff)
Oddly enough, it runs, but the notation doesn't appear correctly. Thank you for working on this!

**Comment by alex65536** [comment]
Hello :)

Sorry for the late reply.

Unfortunately, I don't have the devices with macOS, so cannot test it, but any pull requests are welcome :)

> Project Chess 256 raised exception class 'EResourceReaderWrongFormatException'

Could you please compile with debug information and send me the full stack trace?

>  Oddly enough, it runs, but the notation doesn't appear correctly. Thank you for working on this!

Which widgetset do you use to build the project? Is it native (Cocoa), Qt or GTK? I certainly know that the notation works correctly on Win32 and GTK, but on Qt, the masks work incorrectly, so similar glitches appear. Don't have any idea about macOS native widgets, though.

Also, thanks for testing and trying to run the app under macOS :)

**Comment by relipse** [comment]
I have no idea, I just downloaded Stockfish with home brew and put in those statements and clicked the play button. It starts up with an exception, but if I ignore it, it will start.

**Comment by alex65536** [comment]
What did you use to build the program? And could you please upload the build logs?

**Comment by relipse** [comment]
I opened it in Lazarus and clicked on the green "Play" button, to start it with debugging. Where do I get the build logs? I don't see any option for it.

**Comment by relipse** [comment]
I had it on Current LCL widgetset: "cocoa" then started experimenting with the other ones.
Here is what I think is the build log, please correct me if I am wrong.
[messages.txt](https://github.com/alex65536/Chess256/files/11587584/messages.txt)

**Comment by relipse** [comment]
Furthermore, I tried all these in this screenshot and the notation behaved the same in all of them.
![Greenshot 2023-05-28 21 18 55](https://github.com/alex65536/Chess256/assets/408981/f10facb8-8f6c-459c-b262-1d9feb945ea9)

**Comment by alex65536** [comment]
I hope I have fixed the issues with both `EResourceReaderWrongFormatException` and notation rendering. Could you please pull the latest changes and check if everything is OK now?

**Comment by relipse** [comment]
Thanks for the updates, I am now getting a linker error: https://forum.lazarus.freepascal.org/index.php/topic,63507.0.html
Can't even link.

**Comment by relipse** [comment]
Here is my compiler options command line parameters:
/usr/local/bin/fpc
-MObjFPC
-Scghi
-Crot
-g-h
-k-framework
-kCocoa
-l
-vewnhibq
-vm6058,3124,3123
-Filib/x86_64-darwin
-Fu../../../../.lazarus/lib/units/x86_64-darwin/gtk
-Fu/Applications/Lazarus/lcl/units/x86_64-darwin
-Fu/Applications/Lazarus/components/freetype/lib/x86_64-darwin
-Fu/Applications/Lazarus/components/lazutils/lib/x86_64-darwin
-Fu/Applications/Lazarus/packager/units/x86_64-darwin
-Fu.
-FUlib/x86_64-darwin
-FE../Binary
-o../Binary/Chess256
-dLCL
-dLCLcocoa

**Comment by alex65536** [comment]
The error is about `-lgtk3.0` and it's strange to appear if you use Cocoa. I hope you need to save the project and do a clean build.

**Comment by relipse** [comment]
Nice, I did Run -> Clean up and Build
![Greenshot 2023-05-29 10 03 09](https://github.com/alex65536/Chess256/assets/408981/2686957b-4e6f-435b-a132-11f24357e6f1)
and it is working, with no Exception when it starts, Thank you.

**Comment by alex65536** [comment]
Seems to be resolved, closing the issue.

Thanks for the report :)
